### PR TITLE
Prepare 1.25 support

### PR DESCRIPTION
**Pull request by vxav**
This PR:

- adds the security bundle in version 1.6.2

Towards: https://github.com/giantswarm/giantswarm/issues/29849

### CODE REVIEW

**Review by erkanerol — APPROVED** [review]

**Comment by erkanerol** [comment]
My understanding: We will have a release with this and then bump the version to 1.x and then release another version.  During 1.25 migration, we will use the versions in this specific order. Is it right?

**Comment by vxav** [comment]
You mean a 1.x release for 1.25 and 0.x for 1.24 ?

**Comment by vxav** [comment]
`skip-ci` - Tests run in https://github.com/giantswarm/cluster-vsphere/pull/158#issue-2148711471

**Comment by erkanerol** [comment]
> You mean a 1.x release for 1.25 and 0.x for 1.24 ?
I am trying to understand how we are going to do the migration from 1.24 to 1.25, when we will consume 1.x version and how we manage the versions.

**Comment by vxav** [comment]
Migration:

1. PSS flag=true and default apps to [1.6.2](https://github.com/giantswarm/security-bundle?tab=readme-ov-file#compatibility-matrix)
2. Bump template and k8sVersion in cluster values

**Pull request merged**
