### PR TITLE
Use YAML object for app configuration values

### PR DESCRIPTION
**Pull request by fiunchinho**
Same as https://github.com/giantswarm/default-apps-aws/pull/380

context: https://gigantic.slack.com/archives/C01BYMF6RN0/p1704989737078779

### CODE REVIEW

**Review by vxav — APPROVED** [review]
lgtm

**Comment by QuentinBisson** [comment]
@fiunchinho Can you fix the conflict ?

**Comment by fiunchinho** [comment]
> @fiunchinho Can you fix the conflict ?

done

**Pull request merged**
